---
title: "Dokumentation"
author: "Clara Himmelbauer"
date: "2025-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dieses File dokumentiert alle Arbeitsschritte und sonstige Inputs.

## Wahldaten und deren Aufbereitung

### Die Gemeindeergebnisse von der BMI-Seite herunterladen

- NRW 2024: https://www.bmi.gv.at/412/Nationalratswahlen/Nationalratswahl_2024/start.aspx
- NRW 2019: https://www.bmi.gv.at/412/Nationalratswahlen/Nationalratswahl_2019/start.aspx 

### Gemeindedaten aufbereiten

#### Daten 2024: `data/prep_nrw24.xlsx`
- Absolute Stimmen pro Gemeinde
- Sonstige Zusammenfassen: so = bier + mfg + bge + lmp + gaza + kp + keine
- Dasselbe mit Bezirken und Wahlkarten, man weiß nie für was wir das noch brauchen könnten!

#### Daten 2019: `data/prep_nrw19.xlsx`
- Auf Gebietsstand 2024 bringen: `man/aenderungen_gemeindenummern.xlsx`
    - 62347 Murfeld: Gemeindeteilunga auf 61060 Sankt Veit in der Südsteiermark und 61061 Straß in der Steiermark. Weil Murfeld sehr klein ist und ich nicht genau weiß wie die Gemeinde geteilt wurde (ca 17% - 83% glaub ich), wird das ignoriert
    - 61060 Sankt Veit in der Südsteiermark - GKZ geändert von 61056
    - 61061 Straß in Steiermark - GKZ geändert von 61058
    - 70370 Matrei am Brenner - Zusammenlegung von 70327 Matrei am Brenner, 70330 Mühlbachl, 70341 Pfons
- Absolute Stimmen pro Gemeinde (Gebietsstand 2024), Bezirk, Wahlkarten
- Sonstige Zusammenfassen: so = jetzt + kpö ü wandl + bzö + bier + cpö + gilt + slp

### Beispieldaten erstellen

An einem Wahltag um 17:00 schließen die Wahllokale und die Bundeswahlbehörde (oder Gemeindewahlbehörde) veröffentlicht die Ergebnisse der schon ausgezhälten Gemeinden/Sprengel. Das sind vor allem sehr kleine Gemeinden mit wenigen Wahlberechtigten. Deswegen erstelle ich einen Mock-Datensatz in dem
- Nur 300 Gemeinden ausgezahlt sind, das sind in etwa 14% aller österreichischen Gemeinden
- Alle diese Gemeinden sind sehr klein und haben weniger als 2.000 Wahlberechtigte
Die Berechnung passiert in `analysis/prep_import.R` und das Ergebnis ist `data/in_results-filtered.csv`. 

## Testhochrechnung

1. Nichtwähler berechnen
2. Daten zusammenkopieren (oder 1. udn 2. in umgekehrter Reihenfolge)
3. Ausgezählte Gemeinden filtern/danach sortieren und Daten in ein extra Tabellenblatt kopieren
4. Regressionen rechnen. Das Datenanlyse Add-In muss aktiviert sein. Dazu siehe `man/excel-datenanalyse-aktivieren.docx` 
5. Nach jeder Regression die Koeffizienten in ein extra Tabellenblatt kopieren, oder direkt extra ins prognose-Tabellenblatt.
6. Prognose-Tabellenblatt erstellen:
    - alle Daten rüberkopieren
    - Nach GKZ sortieren (weils schöner ausschaut und mich nicht triggert)
    - Spalten für Prognose vorsehen
    - Daten nach unten schieben und in die frei gewordenen Zeilen über der jeweiligen Partei die Koeffizienten einfügen
7. Prognose rechnen: lineare Gleichung
8. Prognose korrigieren: Keine Werte unter 0, Ausgezählte mit echten Zahlen, Summe der Stimmen = Wahlberechtigte
9. Gesamtergebnis berechnen

## Schwankungsbreite

Die Schwankungsbreite für die Urnenstimmen wird mittels Bootstrapping berechnet. Damit zieht man aus dem ursprünglichen Datensatz ein neues sample mit zurücklegen. Danach schaut man sich an, wie sehr die einzelnen Schätzer voneinenander abweichen und die Standardabweichung ist schließlich die Schwankungsbreite.

## Briefwahl berücksichtigen

*Die Wahlkarte muss spätestens am Wahltag (29. September 2024), 17.00 Uhr, bei der zuständigen Bezirkswahlbehörde einlangen oder bis zu diesem Zeitpunkt in einem Wahllokal des Stimmbezirks der Bezirkswahlbehörde während der Öffnungszeiten des Wahllokals oder bei einer Bezirkswahlbehörde abgegeben worden sein.* https://www.bmi.gv.at/412/Briefwahl.aspx. 

Beim Berücksichtigen der Briefwahl bei Hochrechnungen gibt es zwei Schwierigkeiten.
- Wahlkarten werden auf Bezirksebene ausgezählt
- Briefwählerinnen wählen strukturell anders als die Urnenwähler: Mehr grün, weniger blau.
Hinzu kommt, dass immer mehr Leute per Briefwahl wählen und die strukturellen Unterschiede zwischen Urnenwählerinnen und Biefwählerinnen tendenziell größer werden.

Möglichkeiten damit umzugehen sind:
- Holzhammermethode: Sich anschauen wie die Briefwahlstimmen bei den letzten Wahlen von den Urnenstimmen abgewichen sind. In Erfahrung birngen, wie viele Wahlkarten beantragt wurden. Im Gesamtergebnis bei manchen Parteien was wegnehmen und bei anderen dazugeben.
- Wahlkarten der Vergleichswahl (in dem Fall NRW 2019) versuchen auf Gemeindeebene umzurechnen und somit in die Hochrechnung miteinzubeziehen. Wir haben das mittels Odds-Ratios gemacht. Der sagt uns zum Beispiel in etwa pro Gemeinde wie wahrscheinlich es ist, dass eine Person "grün" gewählt hat wenn sie eine Wahlkarte beantragt hat.

## Clustering

Intuition dahinter: in nicht allen Gemeinden ist

## D'Hondtsches Verfahren

Das D'Hondsche Verfahren nach Höchstzahlenschema wird im Excel `analysis/d'hondt.xlsx` gerechnet. Im `data/master.xlsx` findet sich auch ein entsprechendes Tabellenblatt, um es dann gemeinsam zu rechnen.

Insgesamt wollen wir 183 Sitze im Nationalrat vergeben, davon
- 57 FPÖ
- 51 ÖVP
- 41 SPÖ
- 18 NEOS
- 16 Grüne

Die Berechnung funktioniert folgendermaßen
1. Die Parteienstimmen werden nebeinander geschrieben (alle, nicht nur die Urnenstimmen). Parteien unter der 4%-Hürde werden dabei nicht berücksichtigt.
2. Diese Stimmen werden fortlaufend durch 1, 2, 3, ... geteilt. Die entstehenden Zahlen nennt man Vergleichszahlen
3. Alle Vergleichszahlen untereinander aufschreiben. Im Excel kann man dafür den Befehl `ZUSPALTE` oder auf Englisch `TOCOL` verwenden.
4. Wir sortieren diese Zahlen. Im Excel kann man den Befehl `SORTIEREN` verwenden.
5. Wir suchen die 183. größte Zahl.
6. Die Anzahl der Mandate pro Partei ist nun die Häufigkeit, mit der in den Vergleichszahlen einer Partei eine Zahl welche größer gleich der 183. Zahl ist. Für die NRW 2024 liegt diese Zahl zum Beispiel bei 24.710. In den Vergleichszahlen der FPÖ kommen 57 Zahlen vor, welche größer oder gleich 24.710 sind. Damit hat die FPÖ 57 Mandate.

## Ablauf am Wahlabend

Am Wahlabend muss es schnell gehen, Fernsehsender wollen die Ergebnisse vor ihrer Konkurrenz möglichst schnell nach Wahlschluss veröffentlichen. Das Programm muss also nicht nur die Hochrechnung rechnen, sondern auch:
1. die Daten automatisiert von den Seiten der Wahlbehörden runterladen. Für bundesweite Wahlen können das sein:
    a. Gemeindeergebnisse für fast alle Gemeinden
    b. Sprengelergebnisse für Wien
    c. sprengelergebnisse für Graz
2. Das Format aller dieser Daten ist unterschiedlich, sie müssen vereinheitlicht werden
3. Die Hochrechnung für alle Gebiete/Cluster separat rechnen
4. Die Mandatsverteilung berechnen
5. Checks einbauen, falls mit den Daten etwas nicht passt, zu wenige Daten in einem Cluster vorhanden sind, unplausible Ergebnisse entstehen etc...
6. die Daten nach Freigabe an eine API schicken. Auf diese greift dann die veröffentlichte Stelle zu und speist die Daten automatisch in ihre Grafik ein